gantt
    axisFormat  %m-%d
    title 面试日程
    dateFormat  YYYY-MM-DD
    section SHEIN
    笔试（晚上 8 点）:2021-07-28,1h
    section 百度
    二面（下午 3 点）:baidu, 2021-07-29, 1h
    section 美团
    一面（下午 5 点）:after baidu, 1h
    section 京东
    二面（下午 3 点）: 2021-07-30, 1h
    section 猿辅导
    笔试（下午 7 点）: 2021-07-31, 1h