gantt
    axisFormat  %m-%d
    title 面试日程
    dateFormat  YYYY-MM-DD-H
    section SHEIN
    笔试（晚上 8 点）:done, 2021-07-28-20, 1h
    section 百度
    二面（下午 3 点）:done, 2021-07-29-15, 1h
    section 京东
    二面（下午 3 点）: 2021-07-30-15, 1h
    section 猿辅导
    笔试（下午 7 点）: 2021-07-31-19, 1h
    section 美团
    一面（下午 5 点）:2021-08-03-15, 1h
