name: Generate Job Information README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  issues:
    types: [opened]
  push:
    branches:
      - main
    paths:
      - index.js
      - schedule.js

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: update readme
      run: |
        npm install
        node schedule.js '${{secrets.GCAL_ID}}' '${{secrets.GCAL_CLIENT_ID}}' '${{secrets.GCAL_CLIENT_SECRET}}' '${{secrets.GCAL_ACCESS_TOKEN}}'  '${{secrets.GCAL_REFRESH_TOKEN}}'
        node index.js '${{ secrets.ACCESS_TOKEN }}'
    - name: Commit files
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        commit-message: "(Auto) push new interview schedule"
        rebase: 'true'
        name: 'GitHub Action'
        email: 'actions@github.com'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
